accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/<str:username>/', views.readProfile, name="readProfile"),
    path('update/', views.updateProfile, name="updateProfile"),
    path('delete/', views.deleteProfile, name="deleteProfile"),
]

ecwa/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('register/', include('register.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('jurnal/', include('jurnal.urls')),
    path('accounts/', include('accounts.urls')),
    path('comment/', include('comment.urls')),
    path('forum/', include('forum.urls')),
    path('faq/', include('faq.urls')),
    path('error/', include('error.urls')),
]

faq/urls.py
from django.urls import path

from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.home, name='home'),
    path('update2/', views.update_faq_2, name='update_faq_2'),
    path('update/', views.update_faq, name='update_faq'),
    path('create/', views.create_faq, name='create_faq'),
    path('delete/', views.delete_faq, name='delete_faq'),
]

forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.allthread, name='allthread'),
    path('newthread', views.newthread, name='newthread'),
    path("like/<int:id>",views.like_post,name='like_post'),
    path("delete/<int:id>", views.delete_post, name='delete_post'),
    path("update", views.update_post, name="update_post"),
]

jurnal/urls.py
from django.urls import path

from . import views

app_name = 'jurnal'

urlpatterns = [
    path('', views.jurnal_front, name='jurnal_front'),
    path('add-record/', views.add_record, name='add_record'),
    path('update-record/', views.update_record, name='update_record'),
    path('delete-record/<int:id>/', views.delete_record, name='delete_record'),
    path('drop-record/', views.drop_record, name='drop_record'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Comic+Neue&display=swap" rel="stylesheet">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;700&family=Poppins:wght@400;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <style>
      .home-height {
        min-height: calc(100vh - 56px);
      }
    </style>
	  {% block meta %}
    {% endblock meta %}
  </head>
  
  <body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<div class="container-fluid">
      <a class="navbar-brand font-weight-bold" href="#">
        <img src="https://media.discordapp.net/attachments/882964219371339857/917690478739214366/unknown.png" alt="" width="32" height="32">
      </a>
		  <a class="navbar-brand" href="/">ECWA</a>
		  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-link" href="{% url 'forum:allthread' %}">Forum</a>
          <a class="nav-link" href="{% url 'faq:home' %}">FAQ</a>
            {% if user.is_authenticated %}
            <div class="btn-group">
              <a class="nav-link" href="{% url 'accounts:readProfile' user.username %}">Hi {{ user.profile.name }}!</a>
              <button type="button" class="btn dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'jurnal:jurnal_front' %}">Jurnal</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/accounts/logout/?next=/">Log Out</a>
              </div>
              
            </div>
            {% else %}
            <a class="nav-link" href="/accounts/login/?next=/">Log In</a>
            {% endif %}
        </div>
      </div>
		</div>
	</nav>
  <div class="home-height">
    {% block content %}
    {% endblock %}
  </div>
    
	
    

    <footer class="footer bg-dark text-light text-center py-3">
        &#169 ECWA
    </footer>
	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	{% block script %}
    {% endblock %}
</body>
</html>